### ISSUE TITLE
Por que não abrir o link do pdf em uma nova janela?

### ISSUE THREAD

**Issue by 4n0n1mo** [webmaniabr/NFeWooCommerce#17]
Reparei que já tem o código mas está comentado:

//echo "<script> window.open('{$link_pdf}', '_blank') </script>";

Seria melhor deixar abrir em uma nova janela.

**Comment by 4n0n1mo** [comment]
Fica uma dica de como fiz para abrir em uma nova janela, se quiserem implementar.

Adicionei a query do link do pdf gerado na url e uma ação de chamar a função que abre a url.

Utilizei o código abaixo:

`add_action('admin_footer', 'openNfs');`

```
return $redirect_to = add_query_arg( array(
        'nfs' => urlencode($nfs)
    ), $redirect_to );
```

```
function openNfs(){
	$nfs = urldecode($_REQUEST['nfs']);
	echo "<script>window.open('$nfs', '_blank')</script>";
}
```

**Comment by webmaniabr** [comment]
Obrigado por enviar as informações, verificamos que infelizmente em alguns browsers pode bloquear a abertura do pop-up. No novo commit realizado realizamos uma nova atualização com abertura através do link: https://github.com/webmaniabr/NFeWooCommerce/commit/ac8243ae77299b1c9cdba6ddaa5f404e40d3bac0#diff-e724fd808811611d07953bf5cebf59bd54831bc772746feee9dd1a9887c2f4dbR84.
