### ISSUE TITLE
Emissão de DANFE não funciona em site na AWS

### ISSUE THREAD

**Issue by gabrielmcv** [webmaniabr/NFeWooCommerce#19]
Bom dia a todos!

Realizei a migração do site de um cliente para a AWS e desde então a emissão em lote parou de funcionar.

Depurando o problema, descobri que o file_get_contents não está conseguindo puxar o PDF, como se houvesse um bloqueio impedindo.

`Warning: file_get_contents(https://nfeautomatica.com.br/danfe/32210737881484000135550010000040381193489883/): failed to open stream: HTTP request failed! HTTP/1.1 503 Service Temporarily Unavailable in /htdocs/wp-content/plugins/nota-fiscal-eletronica-woocommerce/class-print.php on line 116`

Fiz o teste com outro url (google.com.br) e ele exibiu, o erro ocorre apenas ao tentar acessar o endereço do nfeautomatica.

Existe alguma regra de firewall impedindo o acesso via AWS?

**Comment by webmaniabr** [comment]
Oi Gabriel, tudo bem? 

Verificamos que o firewall estava bloqueando o acesso de forma incorreta, já publicamos uma atualização para que o acesso ocorra normalmente agora.

Qualquer dúvida estamos aqui. 
Abraço
