### ISSUE TITLE
Variável sempre inacessível

### ISSUE THREAD

**Issue by pa-philos** [webmaniabr/NFeWooCommerce#9]
A variável `$product_type` será sempre inacessível pois está fora de escopo.

https://github.com/webmaniabr/NFeWooCommerce/blob/e3e3744f632877232c8c1f705934f732887b5436/woocommerce_nfe.php#L767

**Comment by webmaniabr** [comment]
@Shirkit a variável $product_type é definida no loop da linha 720.

**Comment by pa-philos** [comment]
Exatamente, e é então usada fora do escopo do Loop. Ela é definida na linha `702`, que o escopo vai até a linha `765`. Depois disso ela sai do escopo e então é referenciada. Claramente ela nunca terá um valor na linha `767` se nada for alterado.
